### PR TITLE
Create game api endpoint & Limit game creation

### PR DESCRIPTION
**Pull request by Jamesllllllllll**
This PR adds two features:

1. Creating a game is now done through a serverless function: a `GET` request to `/api/createGame`
2. This same endpoint also adds a timestamp to the user item field `recentGameTimestamps`

The purpose of `recentGameTimestamps` is to prevent users from spamming public games. The array will only ever hold 3 timestamps, which are the most recently created games. If the oldest timestamp is less than 24 hours before `Date.now()` the user will be prevented from creating a new game.

## Edit:

I added marking each game as private, and also now correctly pre-fetches public and saved games so there is no loading when the user navigates to `/play`

### CODE REVIEW

**Comment by Jamesllllllllll** [comment]
@zackrylangford This is ready for review!

Had some trouble getting Cypress to work in CI - turns out the AWS credentials needed to be passed to GH Actions in order to fetch from the DB.

**Review by zackrylangford — APPROVED** [review]
Looks great, nice work!

**Comment by zackrylangford** [comment]
> @zackrylangford This is ready for review!
> 
> 
> 
> Had some trouble getting Cypress to work in CI - turns out the AWS credentials needed to be passed to GH Actions in order to fetch from the DB.

Let me know if you have any issues with credentials. Since you are writing directly, we can do a more general credential that allows for other backend functionality as well, if needed.

**Comment by Jamesllllllllll** [comment]
Oh, it's all good! I just needed to pass the credentials into GH actions (as secrets/env variables) so Cypress could access them in CI. They just simply weren't there yet and needed to be 😅

**Pull request merged**
